server:
  port: 8085
logging:
  level:
    org.springframework:
      warn
    com.yoti.app:
      debug
---
spring:
  profiles: mock
content_cloud:
  endpoint:
    insertData: http://localhost:23443/content-cloud/v1/insert
    retrieveData: http://localhost:23443/content-cloud/v1/retrieve
    moveDataToBin: http://localhost:23443/content-cloud/v1/move-to-bin
    restoreDataFromBin: http://localhost:23443/content-cloud/v1/restore-from-bin
    removeBinnedObject: http://localhost:23443/content-cloud/v1/remove-binned
    emptyBin: http://localhost:23443/content-cloud/v1/remove-binned

---
spring:
  profiles: dev
content_cloud:
  endpoint:
    insertData: https://localhost:8087/
    retrieveData: https://localhost:8087/
    moveDataToBin: https://localhost:8087/
    restoreDataFromBin: https://localhost:8087/
    removeBinnedObject: https://localhost:8087/
    emptyBin: https://localhost:8087/
